cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "caskroom/versions"
tap "caskroom/fonts"

brew "autoconf"
brew "automake"
brew "ack"
brew "cmake"
brew "curl"
brew "docker"
brew "git"
brew "lsusb"
brew "mas"
brew "openssl"
brew "pandoc"
brew "psgrep"
brew "rsync"
brew "shellcheck"
brew "ssh-copy-id"
brew "wget"

cask "adobe-creative-cloud"
cask "appcleaner"
cask "atom"
cask "cyberduck"
cask "firefox"
cask "flux"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "mactex"
cask "mendeley"
cask "odrive"
cask "onyx"
cask "pdf-expert"
cask "plain-clip"
cask "skype"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"

cask "font-monoid"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-open-sans"
cask "font-inconsolata"
cask "font-inconsolata-for-powerline"

mas "Fantastical 2", id: 975937182
mas "Memory Clean 2", id: 1114591412
mas "Window Focus", id: 1142625137
mas "Slack", id: 803453959
mas "LastPass", id: 926036361
mas "Microsoft Remote Desktop", id: 715768417
mas "Moom", id: 419330170
mas "MPlayerX", id: 421131143
